### ISSUE TITLE
Convert string errors to valid JS Error objects.

### ISSUE THREAD

**Issue by carldanley** [rvagg/ghauth#12]
[Dealing with JSON string errors](https://github.com/rvagg/ghauth/blob/master/ghauth.js#L38-L39) adds extra, unnecessary work for the developer consuming `ghauth`. Is there any way we could convert these to proper JS `Error` objects?

**Comment by rvagg** [comment]
@carldanley if you want to put in a PR I'd be happy to:

1. pass `data.message` as the argument to the `Error` object, so you _should_ have a proper error object with just a string message rather than a stringified JSON object as the message.
2. attach the full `data` object to the created `Error` object somewhere so it's not completely lost, perhaps as a `.data` property.

**Comment by carldanley** [comment]
[PR has been created](https://github.com/rvagg/ghauth/issues/12); closing this in favor of the PR.
